# MIPS Code Generated by Simple Compiler
.data
.newline: .asciiz "\n"
.true_msg: .asciiz "true"
.false_msg: .asciiz "false"
.data
_globalVal: .word 0
.data
_debug: .word 0
.text
_add:
		# Method Prologue
	sw    $ra, 0($sp)		#PUSH
	subu  $sp, $sp, 4
	sw    $fp, 0($sp)		#PUSH
	subu  $sp, $sp, 4
	addu  $fp, $sp, 8
_add_exit:
		# Method Epilogue
	subu  $sp, $fp, 8
	addu  $sp, $sp, 4
	lw    $fp, 0($sp)		#POP
	addu  $sp, $sp, 4
	lw    $ra, 0($sp)		#POP
	jr    $ra
.text
_check:
		# Method Prologue
	sw    $ra, 0($sp)		#PUSH
	subu  $sp, $sp, 4
	sw    $fp, 0($sp)		#PUSH
	subu  $sp, $sp, 4
	addu  $fp, $sp, 8
_check_exit:
		# Method Epilogue
	subu  $sp, $fp, 8
	addu  $sp, $sp, 4
	lw    $fp, 0($sp)		#POP
	addu  $sp, $sp, 4
	lw    $ra, 0($sp)		#POP
	jr    $ra
.text
.globl main
main:	nop		#Start of main
		# Method Prologue
	sw    $ra, 0($sp)		#PUSH
	subu  $sp, $sp, 4
	sw    $fp, 0($sp)		#PUSH
	subu  $sp, $sp, 4
	addu  $fp, $sp, 8
	subu  $sp, $sp, 8
_main_exit:
		# Method Epilogue
	subu  $sp, $fp, 8
	addu  $sp, $sp, 4
	lw    $fp, 0($sp)		#POP
	addu  $sp, $sp, 4
	lw    $ra, 0($sp)		#POP
	li    $v0, 10
	syscall
